### PR TITLE
Updated README.md 

### PR DESCRIPTION
**Pull request by shubhsardana29**
# Beautify README

-   fixes #issue 131

# Proposed Changes

-   Added table of contents

### CODE REVIEW

**Comment by adityabisoi** [comment]
Please remove all the changes except table of contents.

**Comment by shubhsardana29** [comment]
please review it now

**Comment by adityabisoi** [comment]
As I said, please remove all other changes except the table of contents. Be mindful of the spaces/ next lines, which affect the formatting.

**Comment by adityabisoi** [comment]
@shubhsardana29 Updates on this issue?

**Comment by shubhsardana29** [comment]
sorry i was busy with clg exams. 
I have just put the logo of testing, documentation, etc. in the next line because they were  not linking correctly to the table of content if i don't do that so!!

**Comment by adityabisoi** [comment]
You can remove the icons completely, then.

**Comment by shubhsardana29** [comment]
done. please review it now.

**Comment by adityabisoi** [comment]
LGTM

**Pull request merged**
